# Generated by Django 3.2.9 on 2021-12-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hiretubers',
            new_name='Hiretuber',
        ),
    ]
