# Generated by Django 3.2.9 on 2021-12-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_header'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Header',
            new_name='HeaderDetail',
        ),
    ]
