# Generated by Django 3.2.9 on 2021-12-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_aboutustext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutustext',
            old_name='text',
            new_name='description',
        ),
    ]
