# Generated by Django 3.2.9 on 2021-12-31 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_rename_text_aboutustext_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderDetail',
        ),
    ]
