# Generated by Django 3.2.9 on 2021-12-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacttubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttuber',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
